### ISSUE TITLE
BLOCK_BUFFER_SIZE reduced?

### ISSUE THREAD

**Issue by bdurbrow** [MetalWorkerTools/grbl-L-Mega#1]
This is in the config.h for your fork...

`
#define BLOCK_BUFFER_SIZE 34  // Uncomment to override default in planner.h.
`

I was wondering why? RAM use, CPU performance (particularly while threading?), or both?

**Comment by HuubBuis** [comment]
Threading uses a bit of addition ram for storing variables. To be (code) compatible to the Grbl-L version, these variables are defined globally (takes less ram but not so pretty code). To avoid over filling the RAM (will result in crash), the block buffer size is decreased so that **not less** RAM is available as compared to the original Grbl-Mega version. So the reason is to reduce RAM usage.
Unlike a mill, on a lathe there aren't so many Gcodes lines to send so i don't expect any performance penalty.
BLOCK_BUFFER_SIZE is a global setting and effects the block buffer throughout the whole program.
