### ISSUE TITLE
Threading starting point on C-axis shifts when the threading speed (RPM) is changed

### ISSUE THREAD

**Issue by HuubBuis** [MetalWorkerTools/grbl-L-Mega#5]
The threading starting point on the C-axis shifts when the threading speed (RPM) is changed. Seems that this is an issue for quite some time, probably more than a year, so not really a show stopper.   

A workaround is to do all threading passes at the same RPM . That is probably also the usual approach for threading and explains why this issue isn't noticed before!

I have checked Grbl-L but there this isn't an issue. That is strange because the threading code is greatly the same.
I will look in to this and try to fix it. **Until then, do all threading passes at the same RPM**.

**Comment by MetalWorkerTools** [comment]
> I have checked Grbl-L but there this isn't an issue. That is strange because the threading code is greatly the same.

I have checked again and found that Grbl-L has the same issue.

> Seems that this is an issue for quite some time, probably more than a year.

 The issue is in every release of  Grbl-L-Mega and the current release of Grbl-L. I have to check previous releases of Grbl-L.

I measured the error. The "threading starting point shifts 0.4 mm" when changing the feed rate from 75 to 225 mm/min.

will be continued....

**Comment by MetalWorkerTools** [comment]
The issue was caused by the time delay between the synchronization pulse and the processing of the pulse by **protocol_execute_realtime()**. The time difference was quit large at the threading start when de gcode line was processed after waiting for the "first" synchronisation pulse. To fix this, processing of synchronization and index pulses is now partially done in IRQ time.
